### ISSUE TITLE
Error in peak fitting with lmfit 1.1.0

### ISSUE THREAD

**Issue by DanielDosSantosAvila** [LightForm-group/xrdfit#56]
xrdfit version: 1.2.0
lmfit version: 1.1.0

Because of changes in the CompositeModel in the newer versions of lmfit, a KeyError is raised when running the fit_peaks method.

The following code, taken from example 1:

from xrdfit.spectrum_fitting import PeakParams, FitSpectrum

first_cake_angle = 90
file_path = 'example_data/adc_041_7Nb_NDload_700C_15mms_00001.dat'
spectral_data = FitSpectrum(file_path, first_cake_angle)
peak_params = PeakParams((2.75, 2.95), '(10-10)')
spectral_data.fit_peaks(peak_params, 1)

raises the error

Traceback (most recent call last):
  File "/Users/ddossantosavil/opt/anaconda3/envs/xrdfit/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-51a387eef94f>", line 1, in <module>
    runfile('/Users/ddossantosavil/Desktop/TU_Delft/Experimental/XRD/xrdfit/bug.py', wdir='/Users/ddossantosavil/Desktop/TU_Delft/Experimental/XRD/xrdfit')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ddossantosavil/Desktop/TU_Delft/Experimental/XRD/xrdfit/bug.py", line 8, in <module>
    spectral_data.fit_peaks(peak_params, 1)
  File "/Users/ddossantosavil/opt/anaconda3/envs/xrdfit/lib/python3.10/site-packages/xrdfit/spectrum_fitting.py", line 417, in fit_peaks
    new_fit.result = do_pv_fit(stacked_spectrum, peak_param)
  File "/Users/ddossantosavil/opt/anaconda3/envs/xrdfit/lib/python3.10/site-packages/xrdfit/pv_fit.py", line 46, in do_pv_fit
    fit_result = model.fit(intensity, new_fit_parameters, x=two_theta)
  File "/Users/ddossantosavil/opt/anaconda3/envs/xrdfit/lib/python3.10/site-packages/lmfit/model.py", line 1027, in fit
    if not np.isscalar(kwargs[var]):
KeyError: 'background'

This error is caused by the way that the Pseudo-Voigt function is defined. The PV is a sum of a PV model builtin in lmfit, with _x_ as an independent parameter, with a lmfit.Model created from a lambda function defined as lambda background: background. When both of these instances of Model are added, a CompositeModel is created with two independent variables: _x_ and _background_. In the older versions of lmfit, only _x_ was taken as the independent variable in the CompositeModel.

A simple workaround is to change line 32 of pv_fit.py in xrdfit from:
    model += lmfit.Model(lambda background: background)
to:
    model += lmfit.Model(lambda x, background: background)

**Comment by merrygoat** [comment]
Thank you for your comprehensive report on this. Sorry it took me so long to get round to implementing it. A new version is now on Pypi.
